version: '3'

services:
    dbwr:
        build:
            context: docker
            args:
                GIT_TAG: ${GIT_TAG}
                PORT_NUMBER: ${PORT_NUMBER}
        image: dbwr:${DOCKER_TAG}
        container_name: dbwr 
        ports:
            - ${PORT_NUMBER}:${PORT_NUMBER}
        healthcheck:
            test: curl -sS http://localhost:${PORT_NUMBER}/dbwr/ | grep -c "Display Builder Web Runtime" > /dev/null
            timeout: "5s"
            retries: 10

# example of mounting directory with example bob files
#        volumes:
#            - ./examples:/bob
#volumes:
#    bob:
#        driver: local
